CREATE TABLE IF NOT EXISTS generation_mix (
  datetime_utc          TIMESTAMPTZ PRIMARY KEY,
  gas_mw                NUMERIC, 
  coal_mw               NUMERIC, 
  nuclear_mw            NUMERIC, 
  wind_mw               NUMERIC,
  wind_emb_mw           NUMERIC,
  hydro_mw              NUMERIC, 
  imports_mw            NUMERIC, 
  biomass_mw            NUMERIC, 
  other_mw              NUMERIC,
  solar_mw              NUMERIC, 
  storage_mw            NUMERIC, 
  generation_mw         NUMERIC,
  carbon_intensity_gco2_kwh NUMERIC, 
  low_carbon_mw         NUMERIC, 
  zero_carbon_mw        NUMERIC,
  renewable_mw          NUMERIC, 
  fossil_mw             NUMERIC,

  gas_pct               NUMERIC, 
  coal_pct              NUMERIC, 
  nuclear_pct           NUMERIC, 
  wind_pct              NUMERIC,
  wind_emb_pct          NUMERIC,
  hydro_pct             NUMERIC, 
  imports_pct           NUMERIC, 
  biomass_pct           NUMERIC, 
  other_pct             NUMERIC,
  solar_pct             NUMERIC, 
  storage_pct           NUMERIC, 
  generation_pct        NUMERIC,

  ingested_at           TIMESTAMPTZ DEFAULT now()
);
