from sqlalchemy import TIMESTAMP, Column, MetaData, Numeric, Table, text

metadata = MetaData()

generation_mix = Table(
    "generation_mix",
    metadata,
    Column("datetime_utc", TIMESTAMP(timezone=True), primary_key=True),
    Column("gas_mw", Numeric),
    Column("coal_mw", Numeric),
    Column("nuclear_mw", Numeric),
    Column("wind_mw", Numeric),
    Column("wind_emb_mw", Numeric),
    Column("hydro_mw", Numeric),
    Column("imports_mw", Numeric),
    Column("biomass_mw", Numeric),
    Column("other_mw", Numeric),
    Column("solar_mw", Numeric),
    Column("storage_mw", Numeric),
    Column("generation_mw", Numeric),
    Column("carbon_intensity_gco2_kwh", Numeric),
    Column("low_carbon_mw", Numeric),
    Column("zero_carbon_mw", Numeric),
    Column("renewable_mw", Numeric),
    Column("fossil_mw", Numeric),
    Column("gas_pct", Numeric),
    Column("coal_pct", Numeric),
    Column("nuclear_pct", Numeric),
    Column("wind_pct", Numeric),
    Column("wind_emb_pct", Numeric),
    Column("hydro_pct", Numeric),
    Column("imports_pct", Numeric),
    Column("biomass_pct", Numeric),
    Column("other_pct", Numeric),
    Column("solar_pct", Numeric),
    Column("storage_pct", Numeric),
    Column("generation_pct", Numeric),
    Column("ingested_at", TIMESTAMP(timezone=True), server_default=text("now()")),
)
